# Generated by Django 2.2.10 on 2021-06-25 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('resume1', models.FileField(blank=True, null=True, upload_to='')),
                ('resume2', models.FileField(blank=True, null=True, upload_to='')),
                ('upcoming', models.BooleanField(default=True)),
                ('interviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewee', to=settings.AUTH_USER_MODEL)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start', 'end'],
                'unique_together': {('interviewer', 'interviewee', 'end'), ('interviewer', 'interviewee', 'start')},
            },
        ),
    ]
