# Generated by Django 2.2.10 on 2021-06-25 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together=set(),
        ),
    ]
